let language = localStorage.getItem('language')
const languageToggle = document.getElementById('language-switch');


let aboutt = document.getElementById('aboutT');
let experienceE = document.getElementById('experienceE');
let projectsS = document.getElementById('projectsS');
let contactT = document.getElementById('contactT');
let abouttt = document.getElementById('aboutTT');
let experienceEE = document.getElementById('experienceEE');
let projectsSS = document.getElementById('projectsSS');
let contactTT = document.getElementById('contactTT');
let Hello = document.getElementById('Hello');
let Name = document.getElementById('Name');
let Developer = document.getElementById('Developer');
let GetTo = document.getElementById('GetTo');
let AboutMe = document.getElementById('AboutMe');
let experienceEEE = document.getElementById('experienceEEE');
let Inall = document.getElementById('Inall');
let Started = document.getElementById('Started');
let Outline = document.getElementById('Outline');
let years = document.getElementById('years');
let bavaria = document.getElementById('Bavaria');
let Longtext = document.getElementById('Longtext');
let Explore = document.getElementById('Explore');
let Achivements = document.getElementById('Achivements');
let A1 = document.getElementById('A1');
let B1 = document.getElementById('B1');
let C1 = document.getElementById('C1');
let D1 = document.getElementById('D1');
let E1 = document.getElementById('E1');
let E2 = document.getElementById('E2');
let F1 = document.getElementById('F1');
let F2 = document.getElementById('F2');
let Browse = document.getElementById('Browse');
let Projects = document.getElementById('Projects');
let Contact = document.getElementById('Contact');
let about3 = document.getElementById('about3');
let experience3 = document.getElementById('experience3');
let projects3 = document.getElementById('projects3');
let contact3 = document.getElementById('contact3');
let RoleTitle = document.getElementById('RoleTitle');
let RoleDescription = document.getElementById('RoleDescription');
let EE1 = document.getElementById('EE1');
let EE2 = document.getElementById('EE2');
let neoScopeTitle = document.getElementById('neoScopeTitle');
let neoScopeDesc = document.getElementById('neoScopeDesc');
let neoRoleTitle = document.getElementById('neoRoleTitle');
let neoRoleDesc = document.getElementById('neoRoleDesc');
let cultScopeTitle = document.getElementById('cultScopeTitle');
let cultScopeDesc = document.getElementById('cultScopeDesc');
let cultRoleTitle = document.getElementById('cultRoleTitle');
let cultRoleDesc = document.getElementById('cultRoleDesc');
let cultVoiceTitle = document.getElementById('cultVoiceTitle');
let cultVoiceDesc = document.getElementById('cultVoiceDesc');
let umbraScopeTitle = document.getElementById('umbraScopeTitle');
let umbraScopeDesc = document.getElementById('umbraScopeDesc');
let umbraRoleTitle = document.getElementById('umbraRoleTitle');
let umbraRoleDesc = document.getElementById('umbraRoleDesc');
let floatDetailsBtn = document.getElementById('floatDetailsBtn');
let neoTokyoDetailsBtn = document.getElementById('neoTokyoDetailsBtn');
let cultDetailsBtn = document.getElementById('cultDetailsBtn');
let umbraDetailsBtn = document.getElementById('umbraDetailsBtn');
let Support = document.getElementById('Support');
let P1 = document.getElementById('P1');
let P2 = document.getElementById('P2');

const enableLanguage = () => {
    localStorage.setItem('language', 'active')
    aboutt.innerText = "自己紹介"
    experienceE.innerText = "経験"
    projectsS.innerText = "プロジェクト"
    contactT.innerText = "お問い合わせ"
    abouttt.innerText = "自己紹介"
    experienceEE.innerText = "経験"
    projectsSS.innerText = "プロジェクト"
    contactTT.innerText = "お問い合わせ"
    Hello.innerText = "こんにちは、"
    Name.innerText = "ラーズ・ゴーデです"
    Developer.innerText = "ゲーム開発者"
    GetTo.innerText = "もっと知る"
    AboutMe.innerText = "私について"
    experienceEEE.innerText = "経験"
    Inall.innerText = "インディー開発のあらゆる分野で"
    Started.innerText = "17歳で開発を始めました"
    Outline.innerText = "概要"
    years.innerText = "20歳"
    bavaria.innerText = "ドイツ・バイエルン"
    Longtext.innerText = "私は主にUnreal Engineのゲームプレイプログラマーとして活動しており、シェーダー開発においてはテクニカルアーティストの役割も担っております。この分野でのさらなる成長を楽しみにしております。"
    Explore.innerText = ""
    Achivements.innerText = "実績を見る"
    A1.innerText = "最優秀ゲーム賞・最優秀サウンド賞 受賞"
    B1.innerText = "最優秀サウンド賞 受賞"
    C1.innerText = "最優秀サウンド賞 受賞"
    D1.innerText = "受賞"
    E1.innerText = "2026年夏に留学予定"
    E2.innerText = "神奈川大学（日本）にて"
    Link.innerText ="投稿を見るにはこちらをクリック"
    EE1.innerText = "Gamescom 2025 に参加"
    EE2.innerText = "ゲーム: FLOAT"
    AE1.innerText = "GermanDevDays 2025 に参加"
    AE2.innerText = "ゲーム: FLOAT"
    P1.innerText = "プロジェクト概要"
    P2.innerHTML = "- 第3セメスター課題<br>- Gamescom出展のため1ヶ月延長"
    RoleTitle.innerText = "担当役割";
    RoleDescription.innerHTML = "- メインプログラマー<br>- シェーダー開発<br>- エフェクト開発";
    Browse.innerText = "最近の"
    Projects.innerText = "プロジェクトを見る"
    Contact.innerText = "ご連絡ください"
    about3.innerText = "自己紹介"
    experience3.innerText = "経験"
    projects3.innerText = "プロジェクト"
    contact3.innerText = "お問い合わせ"
    neoScopeTitle.innerText = "プロジェクト概要";
    neoScopeDesc.innerText = "- 48時間ゲームジャム";
    neoRoleTitle.innerText = "担当役割";
    neoRoleDesc.innerText = "- メインプログラマー";
    cultScopeTitle.innerText = "プロジェクト概要";
    cultScopeDesc.innerText = "- 第2セメスター課題";
    cultRoleTitle.innerText = "担当役割";
    cultRoleDesc.innerText = "- ソロプロジェクト";
    cultVoiceTitle.innerText = "ボイスアクティング";
    cultVoiceDesc.innerText = "- Thorben Gohde th.gohde@gmail.com による";
    umbraScopeTitle.innerText = "プロジェクト概要";
    umbraScopeDesc.innerHTML = "- 48時間ゲームジャム<br>- その後拡張";
    umbraRoleTitle.innerText = "担当役割";
    umbraRoleDesc.innerHTML = "- プログラマー<br>- シェーダー開発";
    floatDetailsBtn.innerText = "詳細"
    neoTokyoDetailsBtn.innerText = "詳細"
    cultDetailsBtn.innerText = "詳細"
    umbraDetailsBtn.innerText = "詳細"
    Support.innerText = "VarjoによるFLOATのサポート"
}

const disableLanguage = () => {
    localStorage.setItem('language', null)
    aboutt.innerText = "About"
    experienceE.innerText = "Experience"
    projectsS.innerText = "Projects"
    contactT.innerText = "Contact"
    abouttt.innerText = "About"
    experienceEE.innerText = "Experience"
    projectsSS.innerText = "Projects"
    contactTT.innerText = "Contact"
    Hello.innerText = "Hello, I'm"
    Name.innerText = "Lars Gohde"
    Developer.innerText = "Game Developer"
    GetTo.innerText = "Get To Know More"
    AboutMe.innerText = "About Me"
    experienceEEE.innerText = "Experience "
    Inall.innerText = "In all Areas of indie Development"
    Started.innerText = "Started Developing at 17"
    Outline.innerText = "Outline"
    years.innerText = "20 years old"
    bavaria.innerText = "Bavaria, Germany"
    Longtext.innerText = "I’m primarily a gameplay programmer in Unreal Engine, I also wear the tech-art hat for shader development. I’m excited to grow in this field!"
    Explore.innerText = "Explore My"
    Achivements.innerText = "Achievements"
    A1.innerText = "Winner In the categories best game and best sound"
    B1.innerText = "Winner in the category best sound"
    C1.innerText = "Winner in the category best sound"
    D1.innerText = "Winner"
    E1.innerText = "Studying abroad in Summer 2026"
    E2.innerText = "At Kanagawa University, Japan"
    Browse.innerText = "Browse My"
    Projects.innerText = "Recent Projects"
    Contact.innerText = "Contact Me"
    about3.innerText = "About"
    experience3.innerText = "Experience"
    projects3.innerText = "Projects"
    contact3.innerText = "Contact"
    EE1.innerText = "Participating at Gamescom 2025";
    EE2.innerText = "Game: FLOAT";
    RoleTitle.innerText = "My Role";
    RoleDescription.innerHTML = "- Main Programmer<br>- Shader<br>- Effects";
    P1.innerText = "Project Scope"
    P2.innerHTML = "- 3rd Semester Project<br>- Extended by one month for Gamescom";
    AE2.innerText = "Game: FLOAT"
    EE2.innerText = "Game: FLOAT"
    Link.innerText ="Click here to see the post"
    neoScopeTitle.innerText = "Project Scope";
    neoScopeDesc.innerText = "- 48-Hour Game Jam";
    neoRoleTitle.innerText = "My Role";
    neoRoleDesc.innerText = "- Main Programmer";
    cultScopeTitle.innerText = "Project Scope";
    cultScopeDesc.innerText = "- 2nd Semester Project";
    cultRoleTitle.innerText = "My Role";
    cultRoleDesc.innerText = "- Solo Project";
    cultVoiceTitle.innerText = "Voice Acting";
    cultVoiceDesc.innerText = "- By Thorben Gohde th.gohde@gmail.com";
    umbraScopeTitle.innerText = "Project Scope";
    umbraScopeDesc.innerHTML = "- 48-Hour Game Jam<br>- Extended";
    umbraRoleTitle.innerText = "My Role";
    umbraRoleDesc.innerHTML = "- Programmer<br>- Shader";
    floatDetailsBtn.innerText = "Details"
    neoTokyoDetailsBtn.innerText = "Details"
    cultDetailsBtn.innerText = "Details"
    umbraDetailsBtn.innerText = "Details"
    Support.innerText = "Support for FLOAT by Varjo"
}

if(language === "active") {
    enableLanguage();
  } 

languageToggle.addEventListener("click", () =>{
    language = localStorage.getItem('language')
    language !== "active" ? enableLanguage() : disableLanguage()
    console.log(language)
})